### PR TITLE
Fixed accordions in brief section at home page

### LINKED ISSUE #110: '$0 Service Fees' accordion does not open again once is closed
In the web site's home page, when looking at the 'For Free. No Risks' section, if you close the '$0 Service Fees' accordion by opening another one, you are not able to open it again.

Note: the chrome's console shows a js error when clicking these accordions:
TypeError: undefined is not a function

### PR DESCRIPTION
**Pull request by farolfo**
Please note I've made the accordions to open by clicking on ANY section of the panel-heading of the accordion, there for removed the ```<a>``` tag and added the hover to make the text blue.
Fixes #110.

### CODE REVIEW

**Comment by maraoz** [comment]
needs rebase

**Comment by farolfo** [comment]
@maraoz done ;)

**Comment by maraoz** [comment]
Thanks! Will test your branch before merging.

**Comment by yemel** [comment]
ACK, thanks for your contribution @farolfo!

**Pull request merged**
